# File: pubspec.yaml
name: Tproj
description: A mobile application for remote item inspection and delivery services.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  supabase_flutter: ^1.10.25
  image_picker: ^1.0.2
  intl: ^0.18.1
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12
  flutter_local_notifications: ^17.2.3
  google_maps_flutter: ^2.3.1
  http: ^1.1.0
  path_provider: ^2.1.0
  pdf: ^3.10.4
  flutter_pdfview: ^1.3.1

dependency_overrides:
  # Force an updated version of sign_in_with_apple which uses the new Android embedding.
  sign_in_with_apple: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
